### ISSUE TITLE
make a dynamic display for compound interests

### ISSUE THREAD

**Issue by zhangzhongnan928** [TokenScript/TokenScript#234]
make a dynamic display for compound interests

**Comment by jzaki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[__] As a defi user, I want conveniently manage my Compound interests, so that I know I'm making the most of my investments.](https://trello.com/c/45h49wYD/48-as-a-defi-user-i-want-conveniently-manage-my-compound-interests-so-that-i-know-im-making-the-most-of-my-investments)

**Comment by zhangzhongnan928** [comment]
This what I mean
![95F19FF9-BFA8-4F93-A242-DBF9B0B10E68](https://user-images.githubusercontent.com/33795543/64664925-112e3500-d494-11e9-8629-75dd050251e2.gif)
